### ISSUE TITLE
Keybinding for `Docker: Toggle` command

### ISSUE THREAD

**Issue by vasiliy0s** [alanzanattadev/atom-docker#10]
Please add keybinding for this command. 

And, if you can, for `Docker: Select Compose File` command, please.

**Comment by jonarrien** [comment]
+1

**Comment by parserpro** [comment]
+1

**Comment by gfviegas** [comment]
Just add to your keymap.json:

```
'atom-workspace':
  'ctrl-shift-d': 'docker:toggle'
```

in this example, I've attached `ctrl + shift + d` to Docker: Toggle command.

You can do the same to select compose file, just change the command to `docker:select-compose-file`

**Comment by gfviegas** [comment]
@alanzanattadev you may close this

**Comment by alanzanattadev** [comment]
Yes but I understand it's painful to add it manually
