### ISSUE TITLE
support docker machine?

### ISSUE THREAD

**Issue by mackeyja92** [alanzanattadev/atom-docker#11]
Plans on supporting docker machine?

**Comment by alanzanattadev** [comment]
Yes, but I don't have a lot of time in this moment, so I can't promise you a release date for this :) feel free to submit a PR if you want

**Comment by mackeyja92** [comment]
I will look through the code to see if I can find where it is hooking up to the docker host. Essentially we just want it to pull the `DOCKER_HOST` environment variable instead of being `localhost` only.
