### ISSUE TITLE
Support for user not in docker group

### ISSUE THREAD

**Issue by resilva** [alanzanattadev/atom-docker#12]
Adding user to docker group is not a good security practice. This module seems to assumes that the user is in the docker group. If not when selecting a docker-compose file Atom failed to connect to the docker daemon.

Is it possible to find a solution about this and allow to use the plugins without being in the docker group ?

**Comment by alexandernst** [comment]
Adding a user to the docker group on a developer machine (which is where you'd use Atom and this extension) is a perfectly fine security practice.
Moreover, what you're asking here is this module to reinvent the entire (security) wheel on Linux, Windows and Mac?

Probably technically impossible, or if possible, not worth it. I'd close as 'WONTFIX'.
