### ISSUE TITLE
Support For docker-compose version 2

### ISSUE THREAD

**Issue by clickthisnick** [alanzanattadev/atom-docker#18]
Hello, I'm testing this out for the first time and am using docker-compose version 2.

Is there a way for this tool to support this?

**Comment by alanzanattadev** [comment]
Hi,

Normally, we only have to check for the version attribut and adapt parsing for version 2. Unfortunatly, I don't have time to do it and I plan to integrate docker into http://molecule.sh. You can make a PR I'll accept it if you want to :)

**Comment by alexandernst** [comment]
This was fixed by my last PR. It can be closed now.
