### ISSUE TITLE
Add menu options for commands

### ISSUE THREAD

**Issue by jonocodes** [alanzanattadev/atom-docker#20]
Great plugin.

Instead of using the command pallet, perhaps there could be GUI menu items. For example in atom 1.18 see Packages Menu -> Github -> Toggle.

I suppose for this plugin it would be something like:

Packages ->
    Docker -> 
       Toggle
       Select compose file
       Add compose file

**Comment by alanzanattadev** [comment]
Hi,

Actually, I'm focusing on Molecule IDE http://molecule.sh in this moment, trying to get enough APIs to reimplement the docker plugin into Molecule. I won't add features to this one anymore, but if you submit a PR I will review and accept it :)

Good suggestion althought, what you need is in Molecule (Docker isn't supported for now but it will soon enough)

**Comment by jonocodes** [comment]
Molecule looks neat.

PR created

**Comment by alanzanattadev** [comment]
I've merged the PR, I close this issue. Thank you very much for your contribution, you can also contribute to Molecule btw if you want to. DM on twitter / email / issue if you have any question or recommandations or feedback.
