### ISSUE TITLE
Selected file is not a docker-compose file

### ISSUE THREAD

**Issue by mpender** [alanzanattadev/atom-docker#29]
Weird newbie issue.

Atom : 1.27.2 
docker-compose: 1.21.1 
docker-plugin: 0.8.0 

Issue : 

Try to 'select' docker-compose.yml file and it gives the error 'Selected file is not a docker-compose file'
No other way to use docker plugin.

Am I missing something?

**Comment by mpender** [comment]
nevermind... its ymal only and docker-compose.yml (which works with normal docker compose commands )

**Comment by mpender** [comment]
Docs might need to be a bit more explicit in its requirements or allow for .yml ?

**Comment by ernestoe** [comment]
Checking on same issue while exploring this plugin, however it is not clear what did you do to "solve" @mpender. Can you elaborate?
