### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by amcdnl** [alanzanattadev/atom-docker#5]
Maybe I'm just stupid but I can't seem to find how to turn this on/use this. Doesn't show up in context menu or Tools menu. Any thoughts?

**Comment by alanzanattadev** [comment]
Write "compose" in the command palette with your compose file opened in the current buffer, and then type enter on "docker:select-compose-file" in the command palette :)

**Comment by polarathene** [comment]
@alanzanattadev I just ran into this problem myself. It's not immediately clear what to do if you're not used to using packages that way. To avoid confusion for others could you add that little tip on usage to your ReadMe.md?
