### ISSUE TITLE
docker-compose binary can't be found

### ISSUE THREAD

**Issue by jbkc85** [alanzanattadev/atom-docker#6]
"'docker-compose' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."

Working on Mac OS X with Atom 1.7.4 installed.  I have the docker-toolbox installed as well, so docker-compose is in fact in my path.  Any ideas on why its not loading appropriately?  event.js isn't giving much output other than what is pasted above.

**Comment by alanzanattadev** [comment]
Do you use BASH or another shell ? Can you give me the output of "env | grep PATH" command please ? :)

**Comment by jbkc85** [comment]
```
$ echo $0
bash

echo $PATH | grep local
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/usr/local/packer:/usr/local/terraform:/usr/local/bin/google-cloud-sdk/bin
```

**Comment by jbkc85** [comment]
oh, i guess I can also show this:

```
$ which docker-compose
/usr/local/bin/docker-compose
```

**Comment by alanzanattadev** [comment]
Can you open Atom, execute Window Dev Tool command in command palette, and write "process.env.PATH" in the javascript command ? Send me the output please :)

**Comment by jbkc85** [comment]
Ah, that is definitely not updated: 

```
/usr/bin:/bin:/usr/sbin:/sbin
```

I am new to ATOM, so I will see about getting this updated in my editor somewhere :-)

**Comment by alanzanattadev** [comment]
I close this issue because it's unrelated to the docker package :)
