### ISSUE TITLE
Support for multiple compose files (single project)

### ISSUE THREAD

**Issue by OJFord** [alanzanattadev/atom-docker#7]
It would be great if there was support for multiple compose files, i.e.
```sh
$ docker-compose -f file1.yml -f file2.yml CMD
```

Without this it's unfortunately not usable by anyone who uses docker-compose with extending compose files.

This could be by adding a command `Docker: Select Additional Compose File`, for example.

Awesome package though, one less reason to leave Atom! :+1:

**Comment by alanzanattadev** [comment]
Yes, I had to rewrite my compose files because I didn't implemented this feature.
It's already on my todo ;)

**Comment by alanzanattadev** [comment]
Update your docker package to 0.7.0 and you'll see the "docker:add-compose-file" command ;)

**Comment by OJFord** [comment]
Amazing - thank you! Great package.
